apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: flowfile

resources:
  - namespace.yaml
  - secrets.yaml
  - configmap.yaml
  - storage.yaml
  - flowfile-core.yaml
  - flowfile-worker.yaml
  - flowfile-frontend.yaml
  # Uncomment to enable ingress:
  # - ingress.yaml
